name: Generate rules

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 1,6,11,16,21,26 * *"

jobs:
  deploy:
    name: Generate rules
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
    steps:
    - uses: actions/checkout@v4

    - name: Init repo
      shell: bash
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "actions-user@users.noreply.github.com"

    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      shell: bash
      run: |
        sudo apt update
        sudo apt -y install jq unzip gzip

    - name: Commit and push files
      shell: bash
      run: |
        chmod +x ./gen_rules.sh
        bash ./gen_rules.sh
        git add .
        git commit -m "$(date +%F)"
        git push
